// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MwProject.Data;

namespace MwProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210525085419_AddClientToProject")]
    partial class AddClientToProject
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("MwProject.Core.Models.Domains.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("AdminRights")
                        .HasColumnType("bit");

                    b.Property<bool>("CanAcceptProject")
                        .HasColumnType("bit");

                    b.Property<bool>("CanConfirmCalculations")
                        .HasColumnType("bit");

                    b.Property<bool>("CanConfirmEconomicRequirements")
                        .HasColumnType("bit");

                    b.Property<bool>("CanConfirmEstimatedSales")
                        .HasColumnType("bit");

                    b.Property<bool>("CanConfirmGeneralRequirements")
                        .HasColumnType("bit");

                    b.Property<bool>("CanConfirmProject")
                        .HasColumnType("bit");

                    b.Property<bool>("CanConfirmQualityRequirements")
                        .HasColumnType("bit");

                    b.Property<bool>("CanConfirmTechnicalProperties")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditCalculations")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditEconomicRequirements")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditEstimatedSales")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditGeneralRequirements")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditQualityRequirements")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditTechnicalProperties")
                        .HasColumnType("bit");

                    b.Property<bool>("CanModifyProject")
                        .HasColumnType("bit");

                    b.Property<bool>("CanSeeAllProject")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Possition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SuperAdminRights")
                        .HasColumnType("bit");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("MwProject.Core.Models.Domains.Calculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Ckw")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GeneralCostsInPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LabourCosts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Markup")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaterialCosts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrdinalNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("PackingCosts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tkw")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Calculations");
                });

            modelBuilder.Entity("MwProject.Core.Models.Domains.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentSymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrdinalNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MwProject.Core.Models.Domains.CategoryRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Exist")
                        .HasColumnType("bit");

                    b.Property<int>("OrdinalNumber")
                        .HasColumnType("int");

                    b.Property<int>("RequirementId")
                        .HasColumnType("int");

                    b.Property<bool>("ShowValue")
                        .HasColumnType("bit");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("YesNo")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RequirementId");

                    b.ToTable("CategoryRequirements");
                });

            modelBuilder.Entity("MwProject.Core.Models.Domains.CategoryTechnicalProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Exist")
                        .HasColumnType("bit");

                    b.Property<int>("OrdinalNumber")
                        .HasColumnType("int");

                    b.Property<bool>("ShowValue")
                        .HasColumnType("bit");

                    b.Property<int>("TechnicalPropertyId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("YesNo")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TechnicalPropertyId");

                    b.ToTable("CategoryTechnicalProperties");
                });

            modelBuilder.Entity("MwProject.Core.Models.Domains.EstimatedSalesValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("EstimatedSalesValues");
                });

            modelBuilder.Entity("MwProject.Core.Models.Domains.ProductGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrdinalNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductGroups");
                });

            modelBuilder.Entity("MwProject.Core.Models.Domains.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AcceptedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AcceptedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CalculationConfirmedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CalculationConfirmedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Client")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompetitivenessOfTheProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ConfirmedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ConfirmedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Coordinator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionOfPurpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EconomicRequirementsConfirmedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EconomicRequirementsConfirmedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EstimatedCostOfProject")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EstimatedPaybackTimeInMonths")
                        .HasColumnType("int");

                    b.Property<string>("EstimatedSalesConfirmedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EstimatedSalesConfirmedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FinishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneralRequirementsConfirmedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GeneralRequirementsConfirmedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ImplementationTimeInMonths")
                        .HasColumnType("int");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCalculationConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEconomicRequirementsConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEstimatedSalesConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExecuted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGeneralRequirementsConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsQualityRequirementsConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTechnicalProportiesConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("NewAssortment")
                        .HasColumnType("bit");

                    b.Property<bool>("NewProduct")
                        .HasColumnType("bit");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrdinalNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("PercentageOfUsedProductionCapability")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Picture")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("PlannedEndDateOfTheProject")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PlannedProductionVolume")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PlannedStartDateOfTheProject")
                        .HasColumnType("datetime2");

                    b.Property<int>("PriorityOfProject")
                        .HasColumnType("int");

                    b.Property<int>("ProductGroupId")
                        .HasColumnType("int");

                    b.Property<int>("ProductionCapacity")
                        .HasColumnType("int");

                    b.Property<string>("ProjectManagerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("PurposeOfTheProjectId")
                        .HasColumnType("int");

                    b.Property<string>("QualityRequirementsConfirmedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("QualityRequirementsConfirmedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RankingOfEstimatedPaybackTimeInMonths")
                        .HasColumnType("int");

                    b.Property<int>("RankingOfImplementationTimeInMonths")
                        .HasColumnType("int");

                    b.Property<int>("RankingOfReturnOnInvestment")
                        .HasColumnType("int");

                    b.Property<int>("RankingOfUsedProductionCapability")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RealStartDateOfTheProject")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ReturnOnInvestment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TechnicalProportiesConfirmedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TechnicalProportiesConfirmedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Term")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VerificationOperations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ViabilityOfTheProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CompetitivenessOfTheProjectId");

                    b.HasIndex("ProductGroupId");

                    b.HasIndex("ProjectManagerId");

                    b.HasIndex("PurposeOfTheProjectId");

                    b.HasIndex("UserId");

                    b.HasIndex("ViabilityOfTheProjectId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("MwProject.Core.Models.Domains.ProjectRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Exist")
                        .HasColumnType("bit");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("RequirementId")
                        .HasColumnType("int");

                    b.Property<bool>("ShowValue")
                        .HasColumnType("bit");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("YesNo")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RequirementId");

                    b.ToTable("ProjectRequirements");
                });

            modelBuilder.Entity("MwProject.Core.Models.Domains.ProjectTechnicalProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Exist")
                        .HasColumnType("bit");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<bool>("ShowValue")
                        .HasColumnType("bit");

                    b.Property<int>("TechnicalPropertyId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("YesNo")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TechnicalPropertyId");

                    b.ToTable("ProjectTechnicalProperties");
                });

            modelBuilder.Entity("MwProject.Core.Models.Domains.RankingCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbrev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RankingCategories");
                });

            modelBuilder.Entity("MwProject.Core.Models.Domains.RankingElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RangeFrom")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RangeTo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RankingCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RankingCategoryId");

                    b.ToTable("RankingElements");
                });

            modelBuilder.Entity("MwProject.Core.Models.Domains.Requirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrdinalNumber")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Requirements");
                });

            modelBuilder.Entity("MwProject.Core.Models.Domains.TechnicalProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrdinalNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TechnicalProperties");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MwProject.Core.Models.Domains.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MwProject.Core.Models.Domains.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MwProject.Core.Models.Domains.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MwProject.Core.Models.Domains.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MwProject.Core.Models.Domains.Calculation", b =>
                {
                    b.HasOne("MwProject.Core.Models.Domains.Project", "Project")
                        .WithMany("Calculations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MwProject.Core.Models.Domains.CategoryRequirement", b =>
                {
                    b.HasOne("MwProject.Core.Models.Domains.Category", "Category")
                        .WithMany("CategoryRequirements")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MwProject.Core.Models.Domains.Requirement", "Requirement")
                        .WithMany()
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Requirement");
                });

            modelBuilder.Entity("MwProject.Core.Models.Domains.CategoryTechnicalProperty", b =>
                {
                    b.HasOne("MwProject.Core.Models.Domains.Category", "Category")
                        .WithMany("CategoryTechnicalProperties")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MwProject.Core.Models.Domains.TechnicalProperty", "TechnicalProperty")
                        .WithMany()
                        .HasForeignKey("TechnicalPropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("TechnicalProperty");
                });

            modelBuilder.Entity("MwProject.Core.Models.Domains.EstimatedSalesValue", b =>
                {
                    b.HasOne("MwProject.Core.Models.Domains.Project", "Project")
                        .WithMany("EstimatedSalesValues")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MwProject.Core.Models.Domains.Project", b =>
                {
                    b.HasOne("MwProject.Core.Models.Domains.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MwProject.Core.Models.Domains.RankingElement", "CompetitivenessOfTheProject")
                        .WithMany("CompetitivenessOfTheProjects")
                        .HasForeignKey("CompetitivenessOfTheProjectId");

                    b.HasOne("MwProject.Core.Models.Domains.ProductGroup", "ProductGroup")
                        .WithMany()
                        .HasForeignKey("ProductGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MwProject.Core.Models.Domains.ApplicationUser", "ProjectManager")
                        .WithMany("ProjectManagers")
                        .HasForeignKey("ProjectManagerId");

                    b.HasOne("MwProject.Core.Models.Domains.RankingElement", "PurposeOfTheProject")
                        .WithMany("PurposeOfTheProjects")
                        .HasForeignKey("PurposeOfTheProjectId");

                    b.HasOne("MwProject.Core.Models.Domains.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("MwProject.Core.Models.Domains.RankingElement", "ViabilityOfTheProject")
                        .WithMany("ViabilityOfTheProjects")
                        .HasForeignKey("ViabilityOfTheProjectId");

                    b.Navigation("Category");

                    b.Navigation("CompetitivenessOfTheProject");

                    b.Navigation("ProductGroup");

                    b.Navigation("ProjectManager");

                    b.Navigation("PurposeOfTheProject");

                    b.Navigation("User");

                    b.Navigation("ViabilityOfTheProject");
                });

            modelBuilder.Entity("MwProject.Core.Models.Domains.ProjectRequirement", b =>
                {
                    b.HasOne("MwProject.Core.Models.Domains.Project", "Project")
                        .WithMany("ProjectRequirements")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MwProject.Core.Models.Domains.Requirement", "Requirement")
                        .WithMany()
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Requirement");
                });

            modelBuilder.Entity("MwProject.Core.Models.Domains.ProjectTechnicalProperty", b =>
                {
                    b.HasOne("MwProject.Core.Models.Domains.Project", "Project")
                        .WithMany("ProjectTechnicalProperties")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MwProject.Core.Models.Domains.TechnicalProperty", "TechnicalProperty")
                        .WithMany()
                        .HasForeignKey("TechnicalPropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("TechnicalProperty");
                });

            modelBuilder.Entity("MwProject.Core.Models.Domains.RankingElement", b =>
                {
                    b.HasOne("MwProject.Core.Models.Domains.RankingCategory", "RankingCategory")
                        .WithMany("RankingElements")
                        .HasForeignKey("RankingCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RankingCategory");
                });

            modelBuilder.Entity("MwProject.Core.Models.Domains.ApplicationUser", b =>
                {
                    b.Navigation("ProjectManagers");
                });

            modelBuilder.Entity("MwProject.Core.Models.Domains.Category", b =>
                {
                    b.Navigation("CategoryRequirements");

                    b.Navigation("CategoryTechnicalProperties");
                });

            modelBuilder.Entity("MwProject.Core.Models.Domains.Project", b =>
                {
                    b.Navigation("Calculations");

                    b.Navigation("EstimatedSalesValues");

                    b.Navigation("ProjectRequirements");

                    b.Navigation("ProjectTechnicalProperties");
                });

            modelBuilder.Entity("MwProject.Core.Models.Domains.RankingCategory", b =>
                {
                    b.Navigation("RankingElements");
                });

            modelBuilder.Entity("MwProject.Core.Models.Domains.RankingElement", b =>
                {
                    b.Navigation("CompetitivenessOfTheProjects");

                    b.Navigation("PurposeOfTheProjects");

                    b.Navigation("ViabilityOfTheProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
